services:
  solpyra-wallet:
    build:
      context: .
      dockerfile: Dockerfile
    image: solpyra-wallet:1.0.0
    container_name: solpyra-wallet
    ports:
      - "8089:8080"
    env_file:
      - .env
    restart: always
    networks:
      - solpyra

# Use an existing external network
networks:
  solpyra:
    external: true